import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MedPop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div id="navigation">
        <div className='flex justify-between py-2 px-2 border-b-2 border-black'>
          {/* App Icon */}
          <p className='flex items-center justify-center text-xl'>MedPop&reg;</p>
          {/* Join now button */}
          <a className='bg-gray-200 border-2 border-black px-6 py-2 rounded-md hover:scale-[105%] transition-transform' href=''>Get It Now</a>
        </div>
      </div>

      <main className='py-5 px-10 border-2 border-red-500'>
        <section id="landing">
          <div className='flex items-center justify-center mt-16'>
            {/* Device and App Photo */}
            <div className='border-2 border-yellow-500 w-[25rem] h-[25rem] text-center items-center justify-center flex'>Device and Phone Photos</div>
            {/* Introduce */}
            <div className='ml-5'>
              <p className='text-xl font-bold'>MedPop&reg; | Your Adherence Companion </p>
              <br />
              <p className=''>Seamlessly Synced to Your Health Routine. <br />Connect effortlessly, set your schedule, and never miss a dose with <br /> personalized reminders, wherever you are.</p>
              <br />
              <div className='flex space-x-5'>
                <a className='bg-gray-200 border-2 border-black px-6 py-2 rounded-md hover:scale-[105%] transition-transform' href=''>Learn More</a>
                <a className='bg-gray-200 border-2 border-black px-6 py-2 rounded-md hover:scale-[105%] transition-transform' href=''>Get It Now</a>
              </div>
            </div>
          </div>
        </section>

        <section id='device'>
          <div className='flex items-center justify-center mt-[5rem]'>
            {/* Device and App Photo */}
            <div className='border-2 border-yellow-500 w-[25rem] h-[25rem] text-center items-center justify-center flex'>Device Photo</div>
            {/* Introduce */}
            <div className='ml-5 grid grid-cols-2 gap-3'>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
            </div>
          </div>

        </section>

        <section id='phone'>
          <div className='flex items-center justify-center mt-[5rem]'>
            {/* Introduce */}
            <div className='grid grid-cols-2 gap-3'>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
              <div className='bg-gray-200 w-60 h-60 text-center'>a</div>
            </div>
            {/* Device and App Photo */}
            <div className=' ml-5 border-2 border-yellow-500 w-[25rem] h-[25rem] text-center items-center justify-center flex'>Phone Photo</div>
          </div>
        </section>

        <section id='download'>
          <div className='flex items-center justify-center mt-[5rem]'>
            <div>
              <p className='text-xl font-bold text-center'>Transform your health effortlessly. <br /> Dive into MedPop now!</p>
              <div className='flex space-x-5 mt-6 items-center justify-center'>
                <a className='bg-gray-200 border-2 border-black px-6 py-2 rounded-md hover:scale-[105%] transition-transform' href=''>Learn More</a>
                <a className='bg-gray-200 border-2 border-black px-6 py-2 rounded-md hover:scale-[105%] transition-transform' href=''>Get It Now</a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>

  )
}

export default Home
